# Generated by Django 4.1.2 on 2022-10-12 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_company_website_alter_usermaster_is_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='about_us',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='is_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 13, 0, 28, 11, 519146)),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='is_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 13, 0, 28, 11, 519146)),
        ),
    ]
