# Generated by Django 4.1.2 on 2022-10-12 20:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_company_about_us_alter_usermaster_is_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='services',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='is_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 13, 2, 10, 4, 482198)),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='is_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 10, 13, 2, 10, 4, 482198)),
        ),
    ]
