# Generated by Django 4.1.2 on 2022-12-03 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_usermaster_is_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobdetails',
            old_name='company',
            new_name='company_id',
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='is_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 3, 22, 47, 18, 914912)),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='is_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 3, 22, 47, 18, 914912)),
        ),
    ]
