# Generated by Django 4.1.2 on 2022-12-03 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_company_jobdetails_company_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobdetails',
            name='job_position',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='is_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 4, 3, 26, 48, 785521)),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='is_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 4, 3, 26, 48, 785521)),
        ),
    ]
