# Generated by Django 4.1.2 on 2022-12-12 21:20

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_company_country_alter_usermaster_is_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermaster',
            name='is_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 13, 3, 20, 19, 777088)),
        ),
        migrations.AlterField(
            model_name='usermaster',
            name='is_updated',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 13, 3, 20, 19, 777088)),
        ),
        migrations.CreateModel(
            name='AppliedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('jobname', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=500)),
                ('portfolio', models.CharField(max_length=100)),
                ('uni_name', models.CharField(max_length=500)),
                ('major', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('sgpa', models.CharField(max_length=20)),
                ('skill', models.CharField(max_length=500)),
                ('additional_skill', models.CharField(max_length=500)),
                ('cv', models.FileField(upload_to='app/cv')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.candidate')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.jobdetails')),
            ],
        ),
    ]
